### ISSUE TITLE
Pre-build standard GRCh38 mimimap2 index

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#171]
To quote from minimap2 Readme
> For the human reference genome, minimap2 takes a few minutes to generate a minimizer index for the reference before mapping. To reduce indexing time, you can optionally save the index with option -d and replace the reference sequence file with the index file on the minimap2 command line:
> ```
>    minimap2 -d ref.mmi ref.fa                     # indexing
>    minimap2 -a ref.mmi reads.fq > alignment.sam   # alignment
>   ```
> Importantly, it should be noted that once you build the index, indexing parameters such as -k, -w, -H and -I can't be changed during mapping. If you are running minimap2 for different data types, you will probably need to keep multiple indexes generated with different parameters. This makes minimap2 different from BWA which always uses the same index regardless of query data types.

I realized this is one easy optimization we could do as we don't expect to tune the parameters of our mapping steps.

**Comment by kvg** [comment]
Ooh, good idea!

**Comment by kvg** [comment]
I looked into this and it's probably worth skipping this.  Using the index has some unusual side effects (downstream BAMs are identical, but the .bai files are not, which I admit I don't really understand).  But also, the index needs to be recomputed for every different parameter set and then supplied in the input JSON, which makes running the workflow more difficult for the user.  Since the indexing doesn't seem to make a big difference in performance, I think we can skip this.
