### ISSUE TITLE
GuppyRunner not generating outputs of MergeFastq task

### ISSUE THREAD

**Issue by laura-bankers** [broadinstitute/long-read-pipelines#216]
I am using the GuppyRunner workflow to preprocess ONT data on Terra. It does not appear to be generating the expected output files, specifically, the merged fastq file. I think the issue stems from Guppy.wdl, which GuppyRunner imports, there is a task called MergeFastq, but no "call" section for it in the wdl - so I think the problem might be there. I'm new to wdl and Terra so any help is much appreciated.

**Comment by kvg** [comment]
Thanks for the report.  Yep, you're right.  I think we did that because the workflows that we connect it to can use the individual fastq files (which can be nicer for parallelization for tasks like alignment).  Thus, we didn't end up needing the merged one.  But if you need the merged fastq, it should be pretty easy for us to optionally allow merging so you can use it.  Sound good?

**Comment by laura-bankers** [comment]
That sounds great! Thank you so much!

**Comment by kvg** [comment]
Hi Laura,
  I've added a boolean option, 'merge_fastqs', that will combine basecalled fastq files into a "merged.fastq" file. The functionality has been merged into the main branch of the repo, tagged as version 2.1.57, and made available through Dockstore/Terra automatically.

  I think I saw a reference that the version of the workflow you were using was from the branch 'kvg_terra_improvements2'.  This branch is a work in progress for some stuff unrelated to the Guppy basecaller.  I would recommend instead you use the 'main' branch or the tagged version 2.1.57.  For your convenience, I've set the latter to be the default branch in Dockstore.

  Please let me know if the change works or does not work for you.  I'm happy to make adjustments to the workflow to meet your needs.

  Thanks,
    -Kiran
